name: palworld-server-manager
version: '1.0'
summary: Gestionnaire de serveur Palworld
description: |
  Une interface graphique simple et intuitive pour gérer votre serveur Palworld.
  Fonctionnalités :
  - Installation automatique du serveur
  - Démarrage/Arrêt du serveur
  - Sauvegarde automatique
  - Mise à jour du serveur
  - Interface moderne et conviviale

grade: stable
confinement: strict
base: core22

apps:
  palworld-server-manager:
    command: bin/palworld_manager
    plugs:
      - desktop-legacy
      - network
      - network-bind
      - home
      - removable-media
      - x11
      - unity7
      - wayland

parts:
  palworld-server-manager:
    plugin: python
    source: .
    build-packages:
      - python3-dev
      - python3-pip
      - python3-tk
    stage-packages:
      - python3-tk
      - python3-pil
      - python3-pil.imagetk
    python-packages:
      - pillow
      - pyinstaller
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/bin
      cp palworld_manager.py $CRAFT_PART_INSTALL/bin/palworld_manager
      chmod +x $CRAFT_PART_INSTALL/bin/palworld_manager
